### ISSUE TITLE
Need to be able to get field to tell me who is the provider of the activity

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#217] opened 2015-03-31 14:51 UTC
If someone searches for "Bootcamp" there could be multiple orgs offering Bootcamp so I need a field in the results that tells me who is the provider, so that I can display this on mywayfit

**Comment by wszarmach** [comment] 2015-05-29 22:34
Duplicate of #157

**Closed by wszarmach** 2015-05-29 22:34 UTC
Labels: backend, enhancement
