### ISSUE TITLE
Support of abos

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#354] opened 2015-05-15 14:46 UTC
We need to be able to support abos in order to get some providers onto the platform.

The difference of an abo to the activity packages, is that the abo starts the moment the client buys it. The activity packages are defined on specific dates regardless of when the client buys it.

An example of an abo that cannot be handled with what we have at the moment is the 10 class abo. The users gets a reduced price for committing to 10 classes. But they dont usually need to tell the provider which classes they will turn up to at the time of buying the 10 class abo. Sometimes the 10 class abo is unlimited and sometimes it has a time limit. We should be able to support with or without time limit.

For the 10 class abo we cannot force the subscriber to choose the classes he wants to attend when he books it. We could optionally allow him to select them upfront if he wants. But usually the subscriber has no clue which classes he wants to attend at the time of booking. He is only doing it because it is cheaper than him paying for 10 classes individually. I bought a 10 class abo for my running classes for instance. So far I have used 2 of the classes and I am not sure when I will use the other 8, but I am free to use them when I want.

I also saw that one of the gyms who is interested in jasify has the concept of unlimited monthly abos. So you pay a fee and then you can do as many classes as you like that month.

**Comment by pauljanes** [comment] 2015-05-15 14:51
Example from Balboa Move gym where I know one of the trainers:

http://balboamove.ch/preise/

1 Workout, 1 Monat, 3 Monate, 6 Monate, 10 + 1 Workouts

Then they also offer discounts for students. So I can see that we are going to need a way that people can enter a special discount code that the provider gave them for instance. And then they also allow people to suspend their memberships - so for instance there will need to be a way for the provider to extend the end date of the abo if the client is going on holiday for 2 months.

**Comment by wszarmach** [comment] 2015-10-02 18:33
Duplicate of #233

**Closed by wszarmach** 2015-10-02 18:33 UTC
Labels: backend, enhancement, frontend
