### ISSUE TITLE
Add the ability to pay with Jasify credits

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#569] opened 2015-06-30 15:38 UTC
Tons of money will go to Paypal when we go live and that is money that we could be earning ourselves instead if we could offer cheaper payment methods like bank transfers for the larger transactions eg the 12 class package which costs 350CHF (and earns paypal 12CHF in paypal fees)

1) Add an admin-only function that we can credit people with Jasify credits as a first step. This way people can transfer to my account and I can credit their account with Jasify credits. Even though its a bit manual its a good first step.

2) In the payment methods add the option to "Pay with credits" if the user has enough credits in their account to cover the transaction. Eg if transaction if for 25CHF and they have more than 25 credits then offer them "Paypal" or "Pay with Jasify credits". If they have less than 25 credits then do not offer them the "Pay with Jasify credits" option. If they chose to pay with Jasify credits then the "Handling fee" should be removed from the checkout.

I think this would be better for Waldemar to work on than the offering multiple bookings functionality as it is a money saving feature and users love money saving features. It is also great for us if people get used to transferring us money and it can sit in the account for a while earning interest.

**Comment by wszarmach** [comment] 2015-10-02 18:24
Duplicate of #254

**Closed by wszarmach** 2015-10-02 18:24 UTC
Labels: backend, enhancement, frontend
