### ISSUE TITLE
During payment process there is an option to cancel and go back to MyWayFit (even though it was accessed via NoExcuses)

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#418] opened 2015-05-24 11:57 UTC
In the screenshot you see the payment started via Jaynes No Excuses website. Yet the message says Cancel and return to MyWayFit. This needs to display the correct name of the site to which the user will be returned (in this case No Excuses). You can always just say return to and then the url from where the user started.

You can also see there is a label saying MyWayFit on the top left of the screenshot too.

![screen shot 2015-05-24 at 13 53 03](https://cloud.githubusercontent.com/assets/9402268/7787740/6174b0ce-021c-11e5-9b8e-5760d51a45d0.png)

**Comment by pauljanes** [comment] 2015-05-24 11:58
![screen shot 2015-05-24 at 13 56 38](https://cloud.githubusercontent.com/assets/9402268/7787755/002222c4-021d-11e5-8e19-70fff79e6315.png)

**Comment by wszarmach** [comment] 2015-05-24 13:25
Duplicate of #324

**Comment by wszarmach** [comment] 2015-06-25 22:24
After some investigation it seems that these names are taken from the seller account. Can you check if you have configured your account to say MetaFit. Here are the instructions how to check: http://support.getdpd.com/hc/en-us/articles/201283023-My-name-is-shown-instead-of-my-business-company-name-in-PayPal-checkout

**Comment by krico** [comment] 2015-06-25 22:26
I think we generate a web template on paypal, dont Renner Exactly how, but
it's in the initializarion of PayPal service

**Comment by wszarmach** [comment] 2015-06-26 00:21
I changed the business name in PayPal...
![screen shot 2015-06-26 at 02 19 34](https://cloud.githubusercontent.com/assets/9398950/8368385/d8ac5df8-1ba9-11e5-9310-c67df831d958.png)

**Closed** 2015-06-29 19:03 UTC
Labels: blocker, bug, duplicate, frontend, high prio
