### ISSUE TITLE
Date format for fitness providers not ideal

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#685] opened 2015-09-06 22:20 UTC
The view that the admin and org admin get uses the date format mm/dd/yyyy. This is a format sometimes used in the US but for providers such as Jayne and myself too it is very confusing as the UK uses dd/mm/yyyy. Can we display the date based on the user locale or use the same format that we do on the widget.

**Comment by wszarmach** [comment] 2015-09-17 05:11
Duplicate of #553

**Closed by wszarmach** 2015-09-17 05:11 UTC
