### ISSUE TITLE
There is no way to cancel "password assistance" and the modal stays forever

### ISSUE THREAD

**Issue by krico** [krico/jas#281] opened 2015-05-07 23:35 UTC
If you click on "forgot my password" accidentally and then want to cancel it, you can't.  And there is no way of getting that modal out of the way
![image](https://cloud.githubusercontent.com/assets/6952185/7527999/553b4b62-f522-11e4-8169-a0002e48a282.png)

**Comment by wszarmach** [comment] 2015-05-29 22:43
Duplicate of #230

**Closed by wszarmach** 2015-05-29 22:43 UTC
Labels: frontend
