### ISSUE TITLE
If you enter wrong password once, the Sign In button is disabled

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#195] opened 2015-03-23 09:10 UTC
If you enter the wrong password using the email and password login, the Sign In button becomes disabled. This might annoy the users because they might know their password but just have accidentally typed it wrongly.

**Comment by wszarmach** [comment] 2015-03-24 23:47
Duplicate of https://github.com/krico/jas/issues/155

**Closed by wszarmach** 2015-03-24 23:47 UTC
Labels: duplicate
