### ISSUE TITLE
Google account creation triple whammy bug for completeness

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#550] opened 2015-06-24 21:00 UTC
Just for completeness adding the mail that the user sent regarding the chain of bugs that start with jasify google account creation:

Hi Jayne,
 
I tried out the payment system and found a bunch of bugs...
 
(1) When I tried to create an account using Google, I got this error message (notice "Sing In"):
![error1](https://cloud.githubusercontent.com/assets/9402268/8341447/36af1f70-1ac5-11e5-8c89-af2a0fa3841d.png)
 
(2) Then I tried creating an account with email, and I got this error message:
![error2](https://cloud.githubusercontent.com/assets/9402268/8341451/3fff2e9e-1ac5-11e5-9505-576429cba018.png)
 
(3) On the off chance I somehow already had a Jasify account, I tried retrieving a lost password. When I clicked "Forgot your password?" it gave me the error message, "Password is required."
![error3](https://cloud.githubusercontent.com/assets/9402268/8341457/4c777dac-1ac5-11e5-92ed-83b1a1d3aee9.png)
 
I'm using the latest version of Chrome (42.0.2311.135) on Mac OSX.
 
Hope that's helpful. Let me know when you want me to test it again!

**Comment by krico** [comment] 2015-06-27 22:59
I was unable to reproduce this but I think it was related to the cookie/auth problem.  So I will close it as part of that fix.  Please @pauljanes if you know how to reproduce it, test it once I release to prod and reopen if it still occurrs

**Closed** 2015-06-28 08:10 UTC
Labels: blocker
